name: 'Trivy Security Scan'
description: 'Run Trivy vulnerability scanning with configurable options'

inputs:
  subproject:
    description: 'For gradle multi module projects, leave blank for single module projects'
    required: false
    default: ''
  severity:
    description: 'Customisable severity levels'
    required: false
    default: 'HIGH,CRITICAL'
  scan_type:
    description: 'A scan type to use - either image (default) or fs'
    required: false
    default: 'image'
  scanners:
    description: 'A comma-separated list of scanners to use to scan'
    required: false
    default: 'misconfig,vuln,secret'
  location:
    description: 'A location for IaC scans to take place'
    required: false
    default: '.'
  ignore_unfixed:
    description: 'Ignore vulnerabilities that have no current fix'
    required: false
    default: 'true'
  limit_severities_for_sarif:
    description: 'only includes severities as defined in the sarif file'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for authentication'
    required: false
    default: ''

outputs:
  results_count:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.trivy-summary.outputs.results_count }}
  summary:
    description: 'Formatted summary of vulnerabilities'
    value: ${{ steps.trivy-summary.outputs.summary }}
  sarif_upload_outcome:
    description: 'Outcome of the SARIF upload step'
    value: ${{ steps.trivy-upload.outcome }}

runs:
  using: composite
  steps:
    - name: Check repository in helm_deploy/values.yaml
      id: check-package-repo
      shell: bash
      if: inputs.scan_type == 'image'
      run: |
        echo 'checking package repository for ${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject}}:'
        repo_info=$(grep -rh 'repository: ' --include="values.yaml" | grep ${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject}} | head -n1 | awk -F'[:/ ]+' '{print $3"/"$4}')
        echo "repo=${repo_info}" >> $GITHUB_OUTPUT

    - name: Trivy Image Vulnerability Scanner - image
      id: trivy-analyse-image
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
      if: inputs.scan_type == 'image'
      with:
        image-ref: "${{ steps.check-package-repo.outputs.repo }}/${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject}}:latest"
        severity: ${{ inputs.severity }}
        ignore-unfixed: ${{ inputs.ignore_unfixed }}
        skip-dirs: '/usr/local/lib/node_modules/npm'
        skip-files: /app/agent.jar
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 0
        limit-severities-for-sarif: ${{ inputs.limit_severities_for_sarif }}
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2,ghcr.io/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1,ghcr.io/aquasecurity/trivy-java-db:1
        # Set credentials only if using ghcr.io as the image registry and repo is private/internal
        TRIVY_USERNAME: ${{ startsWith(steps.check-package-repo.outputs.repo, 'ghcr.io/') && github.event.repository.visibility != 'public' && github.actor || '' }}
        TRIVY_PASSWORD: ${{ startsWith(steps.check-package-repo.outputs.repo, 'ghcr.io/') && github.event.repository.visibility != 'public' && inputs.github_token || '' }}

    - name: Trivy Image Vulnerability Scanner - filesystem
      id: trivy-analyse-fs
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
      if: inputs.scan_type == 'fs'
      with:
        severity: ${{ inputs.severity }}
        scan-type: ${{ inputs.scan_type }}
        scanners: ${{ inputs.scanners }}
        image-ref: ${{ inputs.location}}
        ignore-unfixed: ${{ inputs.ignore_unfixed }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 0
        limit-severities-for-sarif: ${{ inputs.limit_severities_for_sarif }}
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2,ghcr.io/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1,ghcr.io/aquasecurity/trivy-java-db:1

    - name: Upload trivy artifact
      uses: actions/upload-artifact@v6
      id: trivy-upload-artifact
      with:
        name: trivy-check-${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}
        path: trivy-results.sarif

    - name: Trivy upload sarif
      continue-on-error: true # currently fs scan sarif files aren't valid for Github Advanced security.
      id: trivy-upload
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: 'trivy-results.sarif'
        category: trivy-dependency-check

    - name: Prepare Trivy summary
      id: trivy-summary
      shell: bash
      run: |
        results_count=$(jq '.runs[0].results | length' trivy-results.sarif)
        echo "Vulnerability Summary"
        echo "====================="
        
        if [ "$results_count" -gt 0 ]; then
          jq_output=$(jq -r '.runs[0].results[] | 
            "\(.ruleId)@@\(.message.text | gsub("\\\\"; "\\\\\\\\") | 
            gsub("\""; "\\\"") | gsub("\n"; "@@") |
            gsub("Package: "; "") | gsub("Severity: "; "") | gsub("Installed Version: ";"Installed: ") |
            gsub("Fixed Version: ";"Fixed: "))"' trivy-results.sarif )
          formatted_output=$(echo "${jq_output}" | awk -F@@ '{print $1": "$5" - "$2"\n               ("$3" - "$6")"}' |  sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')
          slack_summary="$(echo "${formatted_output}" | awk '{if (length($0) >= 3000) print substr($0, 1, 2997) "..."; else print $0}')"
        else
          echo "No vulnerabilities found"
          slack_summary="No vulnerabilities found"
        fi
        
        echo "results_count=${results_count}" >> $GITHUB_OUTPUT
        echo "summary=${slack_summary}" >> $GITHUB_OUTPUT
