name: 'Convert NPM Audit to SARIF'
description: 'Converts npm audit-ci json output to SARIF format'
inputs:
  input-file:
    description: 'Input JSON file path'
    required: true
    default: 'npm-security-check-reports.json'
  output-file:
    description: 'Output SARIF file path'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python3 ${{ github.action_path }}/auditjson_to_sarif.py ${{ inputs.input-file }} ${{ inputs.output-file != '' && format('-o {0}', inputs.output-file) || '' }}
