name: 'Create and upload npm outdated reports'
description: 'action to create and upload npm outdated reports'
inputs:
  channel_id:
    description: 'Slack channel ID'
    required: false
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: false
runs:
  using: "composite"
  steps:
  - uses: actions/upload-artifact@v4
    with:
      name: npm-security-check-${{ github.event.repository.name }}
      path: npm-outdated-reports.txt
  - name: run translator
    shell: python {0} npm-outdated-reports.txt >> "$GITHUB_OUTPUT"
    id: translate
    run: |
      import sys
      import json
      import os
      sev_lookup={
        'high':'error',
        'moderate':'warning',
        'low':'note'
      }
      def eprint(*args, **kwargs):
        print(*args, file=sys.stderr, **kwargs)
      def main():
        if len(sys.argv)<2:
          eprint('Usage: python3 outdated_to_slack.py <<input.txt>> [-o output.json]')
          sys.exit(1)
        # Default for output file if required
        args=sys.argv
        input_file=args[1]
        output_file=f"{args[1].split('.')[0]}.json"
        for each_arg in args:
          if each_arg=='-o' and len(args)>(args.index('-o')+1):
            output_file=args[args.index('-o')+1]       
        server_url=os.getenv('server_url')
        repository=os.getenv('repository')
        run_id=os.getenv('run_id')
        workflow=os.getenv('workflow')
        job=os.getenv('job')
        repository_name=os.getenv('repository_name')
        channel_id=os.getenv('channel_id','')
        slack_template = { 
          "channel": f"{channel_id}"
          "text": "npm outdated scan identified issues",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ":warning: Github Actions *npm outdated reports check* ran and identified issues"
              }
            },
            {
              "type": "rich_text",
              "elements": [
                {
                  "type": "rich_text_preformatted",
                  "elements": [
                    {
                      "type": "text",
                      "text": ""
                    }
                  ]
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": f"*Workflow:*\n<{server_url}/{repository}/actions/runs/{run_id}|{workflow}>"
                },
                {
                  "type": "mrkdwn",
                  "text": f"*Job:*\n{job}"
                },
                {
                  "type": "mrkdwn",
                  "text": f"*Repo:*\n{repository}"
                },
                {
                  "type": "mrkdwn",
                  "text": f"*Project:*\n{repository_name}"
                }
              ]
            }
          ]
        }
        results=''
        try:
          with open(input_file) as f:
            results=f.read()
          f.close()     
        except:
          eprint("Encountered an error - please check the input file")
          sys.exit(1)
        if results:
          slack_template['blocks'][1]['elements'][0]['elements'][0]['text']=results 
          with open(output_file,'w') as f:
            json.dump(slack_template, f)
          f.close()
          value='YES'
        else:
          value='NO'
        gh_out = os.environ.get("GITHUB_OUTPUT")
        if gh_out:
            with open(gh_out, "a") as fh:
                fh.write(f"results={value}\n")
            eprint(f"Wrote to $GITHUB_OUTPUT: results={value}")
        else:
            eprint("GITHUB_OUTPUT env var not found")

      if __name__ == '__main__':
        main()

    env:
      server_url: ${{ github.server_url }}
      repository: ${{ github.repository }}
      run_id: ${{ github.run_id }}
      workflow: ${{ github.workflow }}
      job: ${{ github.job }}
      repository_name: ${{ github.event.repository.name }}
      channel_id: ${{ inputs.channel_id }}


  - name: Debug contexts
    shell: bash
    run: |
      echo "steps.translate.outputs.results='${{ steps.translate.outputs.results }}'"
      echo "inputs.channel_id='${{ inputs.channel_id }}'"


  - id: send-slack 
    uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
    if: steps.translate.outputs.results == 'YES' && inputs.channel_id != ''
    with:
      method: chat.postMessage
      token: ${{ inputs.SLACK_BOT_TOKEN }}
      payload-file-path: ./npm-outdated-reports.json
