name: 'Create and upload npm outdated reports'
description: 'action to create and upload npm outdated reports'
inputs:
  channel_id:
    description: 'Slack channel ID'
    required: True
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: True
runs:
  using: "composite"
  steps:
  - uses: actions/upload-artifact@v3
    with:
      name: npm-security-check-${{ github.event.repository.name }}
      path: npm-outdated-reports.txt
  - name: run translator
    shell: bash
    run: python .github/scripts/outdated_to_slack.py npm-outdated-reports.txt
    env:
      server_url: ${{ github.server_url }}
  - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
    with:
      channel-id: ${{ inputs.channel_id}}
      payload-file-path: "./npm-outdated-reports.json"
    env:
      SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
