name: 'Create and upload OWASP dependency reports'
description: 'action to create and upload OWASP dependency reports'
inputs:
  channel_id:
    description: 'Slack channel ID'
    required: True
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: True
runs:
  using: "composite"
  steps:
  - uses: github/codeql-action/upload-sarif@v3
    if: success() || steps.owasp-analyse.conclusion == 'failure'
    with:
      sarif_file: build/reports/dependency-check-report.sarif
      category: gradle-owasp-dependency-check
  - uses: actions/upload-artifact@v3
    if: success() || steps.owasp-analyse.conclusion == 'failure'
    with:
      name: gradle-owasp-dependency-check-${{ github.event.repository.name }}
      path: build/reports/dependency-check-report.html
  - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
    with:
      channel-id: ${{ inputs.channel_id}}
      payload: |
        { "text": "OWASP issues identified",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ":warning: Github Actions *OWASP dependency check* ran and identified issues"
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Code scanning:*\n<${{ github.server_url }}/${{ github.repository }}/security/code-scanning>"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Job:*\n${{ github.job }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Repo:*\n${{ github.repository }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Project:*\n${{ github.event.repository.name }}"
                }
              ]
            }
          ]
        }
    env:
      SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
