name: 'Create and upload OWASP dependency reports'
description: 'action to create and upload OWASP dependency reports'
inputs:
  channel_id:
    description: 'Slack channel ID'
    default: 'NONE'
    required: false
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: false
runs:
  using: "composite"
  steps:
  - uses: github/codeql-action/upload-sarif@v3
    if: success() || steps.owasp-analyse.conclusion == 'failure'
    with:
      sarif_file: build/reports/dependency-check-report.sarif
      category: gradle-owasp-dependency-check
  - uses: actions/upload-artifact@v3
    if: success() || steps.owasp-analyse.conclusion == 'failure'
    with:
      name: gradle-owasp-dependency-check-${{ github.event.repository.name }}
      path: build/reports/dependency-check-report.html
  - uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_codescan_notification@0.2 # WORKFLOW_VERSION
    if: inputs.channel_id != 'NONE'
    with:
      channel_id: ${{ inputs.channel_id}}
      title: "OWASP issues"
      SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
