name: 'Create and upload Trivy dependency reports'
description: 'action to create and upload Trivy dependency reports'
inputs:
  channel_id:
    description: 'Slack channel ID'
    required: True
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: True
runs:
  using: "composite"
  steps:
  - uses: github/codeql-action/upload-sarif@v3
    with:
      sarif_file: 'trivy-results.sarif'
      category: trivy-dependency-check
  - uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_codescan_notification@0.2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ inputs.channel_id}}
      title: "Trivy issues identified"
      SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
