name: 'prepare slack message'
description: 'Takes a text file containing output/results and turns it into a slack-compatible environment variable'
inputs:
  input_file:
    description: "filename to be read into a string"
    required: true
    default: "results.txt"
outputs:
  SLACK_TXT:
    description: "Slack text"
    value: ${{ steps.process-results.outputs.SLACK_TXT }}
runs:
  using: "composite"
  steps:
    - name: Slack - Process Results Text
      id: process-results
      shell: bash
      run: |
        if [[ -f "${{ inputs.input_file }}" ]]; then
          echo "Processing file: ${{ inputs.input_file }}"
          echo "Exporting to env var: ${{ inputs.env_var }}"

          # Escape Slack-sensitive characters but preserve newlines
          SLACK_TXT=$(sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' "${{ inputs.input_file }}")

          # Output multiline value using heredoc
          echo "${{ inputs.env_var }}<<EOF" >> $GITHUB_OUTPUT
          echo "$SLACK_TXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "${{ inputs.env_var }}=no results file (${{ inputs.input_file }}) created" >> $GITHUB_OUTPUT
        fi
