name: 'failure Slack message'
description: 'Sends a slack message to notify of failure'
inputs:
  title:
    description: "Title of the failed workflow"
    required: true
  warningOnly:
    description: "If true then emit a warning, else emit a failure"
    required: true
  channel_id:
    description: "Slack channel to send to"
    required: true
  SLACK_BOT_TOKEN:
    description: "Important slack token"
    required: true
  subproject:
    description: 'For gradle multi module projects, leave blank for single module projects'
    required: false
    default: ''
  summary:
    description: 'A summary of vulnerabilities'
    required: false
    default: '' 
runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1  
      env:
        summary_block: "${{ inputs.summary != '' && format(',{{\"type\": \"section\",\"text\":{{\"type\":\"mrkdwn\",\"text\":\"*Summary*```\\n{0}\\n```\"}}}}', inputs.summary) || '' }}"
      with:
        method: chat.postMessage
        token: ${{ inputs.HMPPS_SRE_SLACK_BOT_TOKEN }}  
        payload: >
          { "channel" : ${{ inputs.channel_id }},
            "text": "*${{ inputs.title }}* ${{ inputs.warningOnly == 'true' && 'issues identified' || 'failed' }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.warningOnly == 'true' && ':warning:' || ':no_entry:' }} Github Workflow ${{ github.workflow }} ${{ inputs.warningOnly == 'true' && 'ran and identified issues' || 'failed' }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Code scanning:*\n<${{ github.server_url }}/${{ github.repository }}/security/code-scanning>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:*\n${{ github.job }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Project:*\n${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}"
                  }
                ]
              }${{ env.summary_block }}
            ]
          }