name: 'prepare slack message'
description: 'Takes a text file containing output/results and turns it into a slack-compatible environment variable'
inputs:
  input_file:
    description: "filename to be read into a string"
    required: true
    default: "results.txt"
outputs:
  SLACK_TXT:
    description: "Slack text"
    value: ${{ steps.process-results.outputs.SLACK_TXT }}
runs:
  using: "composite"
  steps:
  - name: Slack - Process Results Text
    id: process-results
    shell: bash
    run: |
      if [[ -f ${{ inputs.input_file }} ]]; then
        echo "Processing file: ${{ inputs.input_file }}"
        echo "Exporting to env var: ${{ inputs.env_var }}"
        SLACK_TXT=$(cat "${{ inputs.input_file }}" | \
          sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g;' | \
          jq -Rs . | \
          sed -E 's/("$)|(^")//g')
        echo "SLACK_TXT=${SLACK_TXT}" 
        echo "SLACK_TXT=${SLACK_TXT}" >> "$GITHUB_OUTPUT"
      else
        echo "SLACK_TXT=no results file (${{ inputs.input_file }}) created"
        echo "SLACK_TXT=no results file (${{ inputs.input_file }}) created" >> "$GITHUB_OUTPUT"
      fi

