name: Generate postgres database schema report
description: 'action to generate postgres database schema report, requires postgres database running with pipeline'

inputs:
  jdk_tag:
    description: Java version
    default: "21.0"
  database_name:
    default: "postgres"
    description: Name of the database
  host:
    default: "localhost"
    description: Host name of the database
  port:
    default: "5432"
    description: Port number of the database
  schema:
    default: "public"
    description: Schema name
  user:
    default: "root"
    description: Database user name
  password:
    default: "dev"
    description: Database password
  # renovate: datasource=github-releases depName=schemaspy/schemaspy
  schemaspy_version:
    default: "6.2.4"
    description: Schemaspy version
  schemaspy_sha256:
    default: "50abf42c6fbf746b36365f81adb9686e1da83344e89f2719a31e6c1209ebcaad"
    description: SHA256 checksum for SchemaSpy JAR (from GitHub releases)
  # renovate: datasource=maven depName=org.postgresql:postgresql
  postgres_driver_version:
    default: "42.7.3"
    description: Postgres driver version
  postgres_driver_sha256:
    default: "a2644cbfba1baa145ff7e8c8ef582a6eed7a7ec4ca792f7f054122bdec756268"
    description: SHA256 checksum for PostgreSQL JDBC driver

runs:
  using: "composite"
  steps:
    - name: Set up java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        java-version: ${{ inputs.jdk_tag }}
        distribution: 'temurin'

    - uses: ministryofjustice/hmpps-github-actions/.github/actions/setup-schemaspy@v2 # WORKFLOW_VERSION
      with:
        version: ${{ inputs.schemaspy_version }}
        sha256: ${{ inputs.schemaspy_sha256 }}

    - uses: ministryofjustice/hmpps-github-actions/.github/actions/setup-postgres-jdbc@v2 # WORKFLOW_VERSION
      with:
        version: ${{ inputs.postgres_driver_version }}
        sha256: ${{ inputs.postgres_driver_sha256 }}

    - name: Generate database schema report
      shell: bash
      run: |
        java -jar /tmp/schemaspy.jar \
          -t pgsql \
          -dp /tmp/postgres-driver.jar \
          -db ${{ inputs.database_name }} \
          -host ${{ inputs.host }} \
          -port ${{ inputs.port }} \
          -s ${{ inputs.schema }} \
          -vizjs \
          -u ${{ inputs.user }} \
          -p ${{ inputs.password }} \
          -o /tmp/schemaspy
    
    - name: Upload schema report
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: Database Schema Report
        path: /tmp/schemaspy
