name: Security trivy dependency check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:35 UTC

jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml"0.1 # WORKFLOW_VERSION 
    with:
      channel_id: ${{ vars.SLACK_CHANNEL_ID }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
