name: Build docker image & push to registry.

inputs:
  repository_name: 
    description: Repository name
    required: true
    type: string
  docker_registry:
    description: Docker registry
    required: true
    type: string
  registry_org:
    description: Docker registry organisation
    required: true
    type: string
  additional_docker_tag:
    description: Additional docker tag that can be used to specify stable tags
    required: false
    type: string
  push:
    description: Push docker image to registry flag
    required: true
    type: boolean
  app_version: 
    description: App version
    required: true
    type: string
    
secrets:
  HMPPS_QUAYIO_USER:
    required: false 
  HMPPS_QUAYIO_TOKEN:
    required: false 

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Docker login if Docker registry is quay.io
      if: ${{ inputs.docker_registry  == 'quay.io' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ secrets.HMPPS_QUAYIO_USER }}
        password: ${{ secrets.HMPPS_QUAYIO_TOKEN }}
        
    - name: Docker login if Docker registry is ghcr.io
      if: ${{ inputs.docker_registry  == 'ghcr.io' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker images 
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        push: ${{ inputs.push }}
        provenance: false
      build-args: |
        "BUILD_NUMBER=${{ inputs.app_version }}"
        "GIT_REF=$${{ github.head_ref }}"
        "GIT_BRANCH=$${{ github.ref_name }}"
      tags: |
        ${{ inputs.docker_registry}}/${{ inputs.registry_org }}/${{ github.event.repository.name }}:latest
        ${{ inputs.docker_registry}}/${{ inputs.registry_org }}/${{ github.event.repository.name }}:${{ inputs.app_version }}
