name: Build docker image & push to registry.

inputs:
  repository_name: 
    description: Repository name
    required: true
    type: string
  docker_registry:
    description: Docker registry
    required: true
    type: string
  registry_org:
    description: Docker registry organisation
    required: true
    type: string
  additional_docker_tag:
    description: Additional docker tag that can be used to specify stable tags
    required: false
    type: string
  push:
    description: Push docker image to registry flag
    required: true
    type: boolean
  app_version: 
    description: App version
    required: true
    type: string
  docker_registry_username:
    description: Docker registry username
    required: true
    type: string
  docker_registry_token:
    description: Docker registry username
    required: true
    type: string
  git_head_ref:
    description: git head ref 
    required: true
    type: string
  git_ref_name:
    description: git branch name
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set version
      run: |
        echo "version=$app_version" | tee -a "$GITHUB_OUTPUT"
        
    # - uses: actions/checkout@v4
    # - uses: docker/setup-qemu-action@v2
    # - uses: docker/setup-buildx-action@v2

    # - name: Docker login if Docker registry is quay.io
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ${{ inputs.docker_registry }}
    #     username: ${{ inputs.docker_registry_username }}
    #     password: ${{ inputs.docker_registry_token }}

    # - name: Build Docker images 
    #   uses: docker/build-push-action@v4
    #   with:
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     platform: linux/amd64,linux/arm64
    #     context: .
    #     push: ${{ inputs.push }}
    #     provenance: false
    #     build-args: |
    #       "BUILD_NUMBER=${{ inputs.app_version }}"
    #       "GIT_REF=${{ inputs.git_head_ref }}"
    #       "GIT_BRANCH=${{ inputs.git_ref_name }}"
    #     tags: |
    #       ${{ inputs.docker_registry}}/${{ inputs.registry_org }}/${{ inputs.repository_name }}:latest
    #       ${{ inputs.docker_registry}}/${{ inputs.registry_org }}/${{ inputs.repository_name }}:${{ inputs.app_version }}
