name: Build & push docker image and deploy to environment. 

on:
  workflow_call:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        type: string
      registry_org:
        description: Docker registry organisation
        required: true
        type: string
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        type: boolean
      docker_multiplatform:
        description: Docker image build multiplatform or not
        required: true
        type: boolean
        default: true

    secrets:
      HMPPS_QUAYIO_USER:
        required: false 
      HMPPS_QUAYIO_TOKEN:
        required: false 

permissions:
  contents: read
  packages: write

jobs:
  create_app_version:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.create_app_version.outputs.version }}
    steps:
      - name: Set version
        id: create_app_version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"

  docker_build:
    name: Build docker image
    needs: [ create_app_version ]
    runs-on: ubuntu-latest
    steps:
      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_docker@feat/HEAT-344-share-app-version-across-jobs
        if: ${{ ( inputs.docker_registry  == 'ghcr.io' ) && ( ! inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ inputs.push }}
          app_version: ${{ needs.create_app_version.outputs.version }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_docker@feat/HEAT-344-share-app-version-across-jobs
        if: ${{ ( inputs.docker_registry  == 'quay.io' ) && ( ! inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ inputs.push }}
          app_version: ${{ needs.create_app_version.outputs.version }}
          HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
          HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN}}
          git_head_ref: ${{ github.head_ref }}
          git_branch_ref: ${{ github.ref_name }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_multiplatform_docker@feat/HEAT-344-share-app-version-across-jobs
        if: ${{ ( inputs.docker_registry  == 'ghcr.io' ) && ( inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ inputs.push }}
          app_version: ${{ needs.create_app_version.outputs.version }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_multiplatform_docker@feat/HEAT-344-share-app-version-across-jobs
        if: ${{ ( inputs.docker_registry  == 'quay.io' ) && ( inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ inputs.push }}
          app_version: ${{ needs.create_app_version.outputs.version }}
          HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
          HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN}}
          git_head_ref: ${{ github.head_ref }}
          git_branch_ref: ${{ github.ref_name }}



