name: Build docker image, test and deploy to environments. 

on:
  workflow_call:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        type: string
      registry_org:
        description: Docker registry organisation
        required: true
        type: string
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  create_app_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_app_version.outputs.version }}
    steps:
      - name: Set version
        id: create_app_version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"

  docker_build:
    name: Build docker image
    needs: [ create_app_version ]
    runs-on: ubuntu-latest
    steps:
      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_docker.yml
        with:
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ inputs.push }}
          app_version: ${{ needs.create_app_version.outputs.version }}