name: Create app version to use it for docker build and deploy pipelines 

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.create_app_version.outputs.version }}

jobs:
  create_app_version:
    name: Docker build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_app_version.outputs.version }}
    steps:

      - name: Set version
        id: version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"