name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      environment: 
        description: Environment
        required: true 
        type: string
      app_version:
        description: App version
        required: true 
        type: string
      k8s_deployment_name:
        description: Kubernetes deployment name
        default: "PROJECT_NAME"
        required: false
        type: string
      changelog_git_paths:
        description: Changelog git paths
        required: false
        default: ""
        type: string
      show_changelog:
        description: Show changelog
        default: true
        required: false
        type: boolean
      slack_notification:
        description: Slack notification
        default: true
        required: false
        type: boolean
      helm_additional_args:
        description: Helm additional args
        default: ""
        required: false
        type: string
      helm_timeout:
        description: Helm timeout
        default: "5m"
        required: false
        type: string
      helm_dir:
        description: Helm dir
        default: "helm_deploy"
        required: false
        type: string

permissions:
  contents: read

jobs:

  deploy_env:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: latest
     
      - name: Set Slack Channel ID
        id: set-slack-channel-id
        run: |
          if [[ "${{ inputs.environment }}" == "prod" ]]; then
            echo "slack_channel_id=${{ vars.PROD_RELEASES_SLACK_CHANNEL }}" | tee -a $GITHUB_OUTPUT
          else
            echo "slack_channel_id=${{ vars.NONPROD_RELEASES_SLACK_CHANNEL }}" | tee -a $GITHUB_OUTPUT
          fi

      - name: Check for IP_ALLOWLIST_GROUPS_YAML
        id: check-ip-allowlists
        run: |
          if [[ -n "${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_YAML }}" ]]; then
            echo "${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_YAML }}" | base64 --decode > ip-allowlist-groups.yaml
            echo "ALLOWLIST_GROUPS=--values ./ip-allowlist-groups.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Check for IP_ALLOWLIST_GROUPS_VERSION
        id: check-ip-allowlists-version
        run: |
          if [[ -n "${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_VERSION }}" ]]; then
            echo "ALLOWLIST_VERSION=--set generic-service.allowlist_version=${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_VERSION }}" >> $GITHUB_OUTPUT
          fi

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-deploy@HEAT-491-ip-allowlists # WORKFLOW_VERSION
        id: deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.app_version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}
          k8s_deployment_name: ${{ inputs.k8s_deployment_name }}
          changelog_git_paths: ${{ inputs.changelog_git_paths }}
          show_changelog: ${{ inputs.show_changelog }}
          helm_additional_args: ${{ inputs.helm_additional_args }}
          helm_timeout: ${{ inputs.helm_timeout }}
          helm_dir: ${{ inputs.helm_dir }}
          helm_allowlist_groups: ${{ steps.check-ip-allowlists.outputs.ALLOWLIST_GROUPS }}
          helm_allowlist_version: ${{ steps.check-ip-allowlists-version.outputs.ALLOWLIST_VERSION }}

      # Notification bit - always send prod releases to dps-releases - CVA3MKDTR
      - if: ${{ always() && ( inputs.environment == 'prod' || inputs.environment == 'production' ) }}
        id: prod-dps-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v2 # WORKFLOW_VERSION
        with:
          channel_id: 'CVA3MKDTR'
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          deployment_changelog: ${{ steps.deploy.outputs.deployment_changelog }}


      # Optional prod releases slack channel (using PROD_RELEASES_SLACK_CHANNEL variable)
      - if: ${{ always() && ( inputs.slack_notification && steps.set-slack-channel-id.outputs.slack_channel_id != '' ) }}
        id: send-release-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v2 # WORKFLOW_VERSION
        with:
          channel_id: ${{ steps.set-slack-channel-id.outputs.slack_channel_id }}
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          deployment_changelog: ${{ steps.deploy.outputs.deployment_changelog }}
