name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      environment: 
        description: Environment
        required: true 
        type: string
      app_version:
        description: App version
        required: true 
        type: string
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string

    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: Slack bot token
        required: false

permissions:
  contents: read

jobs:
  get_environment:
    name: Get environment 
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Get environment details 
        id: env
        run: |
          case ${{ inputs.environment }} in
            'development') environment='dev' ;;
            'dev') environment='dev' ;;
            'preprod') environment='preprod' ;;
            'preproduction') environment='preprod' ;;
            'prod') environment='prod' ;;
            'production') environment='prod' ;;     
            *) environment='invalid' ;;
          esac
          echo "environment=${environment}" | tee -a "$GITHUB_OUTPUT"

  deploy_env:
    name: Deploy to ${{ inputs.environment }}
    needs: [ get_environment ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: ${{ needs.get_environment.outputs.environment}}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: latest
      - uses:  ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-deploy@feat/HEAT-344-create-deploy_env_workflow
        with:
          environment: ${{ needs.get_environment.outputs.environment}}
          version: ${{ inputs.app_version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}

  slack_notify:
    name: Notify slack if deploy_env job failed 
    runs-on: ubuntu-latest
    needs: [ deploy_env ]
    if: ${{ jobs.deploy_env.outcome == 'failure' }}
    steps:
      - name: Notify slack on failure of job  
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        if: ${{ inputs.channel_id != 'NO_SLACK' }}
        with:
          channel-id: ${{ inputs.channel_id }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}