name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      environment: 
        description: Environment
        required: true 
        type: string
      app_version:
        description: App version
        required: true 
        type: string

permissions:
  contents: read

jobs:

  deploy_env:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: latest
      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-deploy@v1 # WORKFLOW_VERSION
        id: deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.app_version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}
        continue-on-error: true

      # Notification bit - always send prod releases to dps-releases - CVA3MKDTR
      - if: ${{  inputs.environment == 'prod' || inputs.environment == 'production' }} 
        id: prod-dps-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v1 # WORKFLOW_VERSION 
        with:
          channel_id: 'CVA3MKDTR'
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}

      
      # Optional prod releases slack channel (using PROD_RELEASES_SLACK_CHANNEL variable)
      - if: ${{ ( inputs.environment == 'prod' || inputs.environment == 'production' ) && vars.PROD_RELEASES_SLACK_CHANNEL != '' }}
        id: prod-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v1 # WORKFLOW_VERSION 
        with:
          channel_id: ${{ vars.PROD_RELEASES_SLACK_CHANNEL }}
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}

      # Optional non-prod releases slack channel (using NONPROD_RELEASES_SLAC_CHANNEL variable)
      - if: ${{ (inputs.environment != 'prod' && inputs.environment != 'production') &&  vars.NONPROD_RELEASES_SLACK_CHANNEL != '' }}
        id: nonprod-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@HEAT-429_slack_notification_on_deploy # WORKFLOW_VERSION 
        # uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v1 # WORKFLOW_VERSION 
        with:
          channel_id: ${{ vars.NONPROD_RELEASES_SLACK_CHANNEL }}
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}