on:
  workflow_call:
    inputs:
      jdk_version:
        required: true
        type: string
      postgres_db:
        required: true
        type: string
      postgres_username:
        required: true
        type: string
      postgres_password:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ inputs.postgres_db }}
          POSTGRES_USER: ${{ inputs.postgres_username }}
          POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ inputs.postgres_username }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      localstack:
        image: localstack/localstack:3
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.jdk_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # may require changing 
          java-version: ${{ inputs.jdk_version }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get -y install awscli
          aws --version

      - name: Wait for LocalStack to be ready
        run: |
          curl -4 --connect-timeout 30 --retry-connrefused --retry 2 --retry-delay 5 http://localhost:4566

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Run validation
        run: ./gradlew validate
