name: Integration tests

on:
  workflow_call:
    inputs:
      npm_script:
        description: 'The main test script to execute with `npm run`'
        required: false
        type: string
        default: 'int-test'
      shard_count:
        description: 'Number of parallel Cypress or Playwright test shards to run (1-6)'
        required: false
        type: number
        default: 1
      test_results_artifact_name:
        description: 'Name of uploaded test results artifact; must be unique across pipeline (eg. in matrix strategies for parallelised tests)'
        required: false
        type: string
        default: 'npm_integration_test_artifacts'
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
      redis_tag:
        description: 'Optionally, start a redis service with this tag'
        required: false
        type: string
      wiremock_port:
        description: 'The port number to run wiremock on'
        required: false
        type: number
        default: 9091

permissions:
  contents: read

jobs:
  integration_test:
    name: Run the integration tests${{ inputs.npm_script == 'int-test' && '' || format(' – {0}', inputs.npm_script) }}${{ inputs.shard_count == 1 && '' || format(' – shard {0}/{1}', matrix.shard, inputs.shard_count) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: >-
          ${{
            fromJSON(
              inputs.shard_count == 2 && '[1,2]' ||
              inputs.shard_count == 3 && '[1,2,3]' ||
              inputs.shard_count == 4 && '[1,2,3,4]' ||
              inputs.shard_count == 5 && '[1,2,3,4,5]' ||
              inputs.shard_count == 6 && '[1,2,3,4,5,6]' ||
              '[1]'
            )
          }}
    services:
      redis:
        image: ${{ inputs.redis_tag && format('redis:{0}', inputs.redis_tag) || '' }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Check out the shared workflow runner
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .hmpps-github-actions
          persist-credentials: false
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: npm_build_artifacts
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: Init testing framework if necessary
        run: npm run int-test-init:ci --if-present
      - uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/tool-installers/setup-wiremock@97eeedc606b4ce163133d203259a71698c9ad34b # v1.0.16
      - name: Prepare and run integration tests
        id: integration-tests
        env:
          NPM_SCRIPT: ${{ inputs.npm_script }}
          SHARD_COUNT: ${{ inputs.shard_count }}
          SHARD_INDEX: ${{ matrix.shard }}
          WIREMOCK_PORT: ${{ inputs.wiremock_port }}
        run: node .hmpps-github-actions/.github/scripts/run-node-integration-tests.mjs
      - name: upload results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.shard_count == 1 && inputs.test_results_artifact_name || format('{0}-shard-{1}', inputs.test_results_artifact_name, matrix.shard) }}
          path: |
            integration_tests/videos/
            integration_tests/screenshots/
            coverage/
            test_results/
            ctrf/
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3
        with:
          artifact: ${{ inputs.shard_count == 1 && inputs.test_results_artifact_name || format('{0}-shard-{1}', inputs.test_results_artifact_name, matrix.shard) }}
          name: ${{ inputs.shard_count == 1 && 'Test Report' || format('Test Report – shard {0}/{1}', matrix.shard, inputs.shard_count) }}
          path: 'test_results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
      - name: fail the action if the tests failed
        if: ${{ steps.integration-tests.outcome == 'failure' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            core.setFailed('Integration tests failed')
