name: Security OWASP dependency check

on:
  workflow_call:
    inputs:
      channel_id:
        required: false
        default: 'NO_SLACK'
        type: string
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: Slack bot token
        required: false

permissions:
  contents: read

jobs:
  security-owasp-check:
    name: Security OWASP dependency check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      # parent_directory: ${{ github.event.repository.name == '' && '.' || github.event.repository.name}}
      serif_directory:  "${{ github.event.repository.name == '' && '.' || github.event.repository.name}}"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    # - name: Run gradle OWASP Dependency Check Update
    #   id: owasp-update
    #   run: ./gradlew dependencyCheckUpdate --info
    - name: Run gradle OWASP Dependency Check Analyse
      id: owasp-analyse
      run: ./gradlew dependencyCheckAnalyze --info
      continue-on-error: true

    - uses: ministryofjustice/hmpps-github-actions/.github/actions/security_owasp_reports@0.2 # WORKFLOW_VERSION
      if: steps.owasp-analyse.outcome == 'failure'
      with:
        channel_id: ${{ inputs.channel_id }}
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}

    - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      if: steps.owasp-analyse.conclusion == 'failure' && inputs.channel_id != 'NO_SLACK'
      with:
        channel-id: ${{ inputs.channel_id}}
        payload: |
          { "text": "Owasp check failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":no_entry: Failed GitHub Action:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:*\n${{ github.job }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Project:*\n${{ github.event.repository.name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
