name: Sentry release and deploy

on:
  workflow_call:

    inputs:
      sentry_org:
        default: ministryofjustice
        required: false
        type: string
        description: "The organisation into which Sentry is being installed"
      sentry_project:
        required: true
        type: string
        description: "The project into which Sentry is being installed"
      sentry_environment:
        required: true
        type: string
        description: "The environment into which Sentry is being installed"
      sentry_create_release:
        default: 'false'
        type: string
        required: false
        description: "Tell sentry-cli to work out the commits on this release - this should only be done ONCE, ideally when you push to DEV."
      app_version:
        type: string
        required: true
        description: "The version of the app being deployed"

permissions:
  contents: read

jobs:
  sentry-install:
    name: Sentry install
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ inputs.sentry_org }}
      SENTRY_PROJECT: ${{ inputs.sentry_project }}
      APP_VERSION: ${{ inputs.app_version }}
      SENTRY_ENVIRONMENT: ${{ inputs.sentry_environment }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Sentry - Setup environment
        shell: bash
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
      - name: Create release
        if: ${{ inputs.sentry_create_release == 'true' }}
        shell: bash
        run: |
          sentry-cli releases new "${APP_VERSION}" --project "${SENTRY_PROJECT}"
          sentry-cli releases set-commits "${APP_VERSION}" --auto
          sentry-cli releases finalize "${APP_VERSION}"
      - name: Sentry - Record deployment
        shell: bash
        run: |
          sentry-cli releases deploys "${APP_VERSION}" new -e "${SENTRY_ENVIRONMENT}"
