name: Test - helm lint

on:
  workflow_call:
    inputs:
      environment:
        description: environment for deployment
        required: false
        default: 'dev'
        type: string
      chart_name:
        description: name of the helm chart - defaults to the repo name
        required: false
        default: ${{ github.event.repository.name  }}
        type: string
      helm_dir:
        description: directory of the helm charts
        required: false
        default: 'helm_deploy'
        type: string
      helm_additional_args:
        required: false
        default: ''
        type: string
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false

permissions:
  contents: read

jobs:
  helm_lint:
    name: Helm lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/tool-installers/setup-helm@e0e6abc2f67f2bbb81a74610d6c307ab468a1a77 # v1
    - name: 'Run helm lint commands'
      shell: bash
      run: | 
          cd ${{ inputs.helm_dir }}
          helm dependency update "${{ inputs.chart_name }}"
          helm lint "${{ inputs.chart_name }}" --values=values-"${{ inputs.environment }}".yaml ${{ inputs.helm_additional_args }}
