name: Test - helm lint

on:
  workflow_call:
    inputs:
      environment:
        description: environment for deployment
        required: false
        default: 'dev'
        type: string
      chart_name:
        description: name of the helm chart - defaults to the repo name
        required: false
        default: ${{ github.event.repository.name  }}
        type: string
      helm_dir:
        description: directory of the helm charts
        required: false
        default: 'helm_deploy'
        type: string
      helm_additional_args:
        required: false
        default: ''
        type: string
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false

permissions:
  contents: read

jobs:
  helm_lint:
    name: Helm lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/tool-installers/setup-helm@35bb5e74a025299cddf50909c1968444d966c1dc # v1.0.21
    - name: 'Run helm lint commands'
      shell: bash
      env:
        HELM_DIR: ${{ inputs.helm_dir }}
        CHART_NAME: ${{ inputs.chart_name }}
        ENVIRONMENT: ${{ inputs.environment }}
        HELM_ADDITIONAL_ARGS: ${{ inputs.helm_additional_args }}
      run: | 
          set -euo pipefail

          cd "${HELM_DIR}"
          helm dependency update "${CHART_NAME}"

          extra_args=()
          if [[ -n "${HELM_ADDITIONAL_ARGS}" ]]; then
            read -r -a extra_args <<< "${HELM_ADDITIONAL_ARGS}"
          fi

          helm lint "${CHART_NAME}" --values "values-${ENVIRONMENT}.yaml" "${extra_args[@]}"
